---
title: "Final Project of MSDS 597"
author: "Hui Wang"
date: "5/4/2020"
output:
  html_document:
    df_print: paged
  word_document: default
  pdf_document: default
geometry: margin=1in
fontsize: 11pt
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.height = 6)
options(tinytex.verbose = TRUE)
library(dplyr)
library(tidyverse)
library(tidytext)
library(lubridate)
library(xml2)
library(rvest)
library(stringr)
library(rvest)
library(gutenbergr)   # for the text 
library(tidyr)   # for separate_rows
library(gridExtra)    #to make side-by-side figure
library(choroplethr)
library(choroplethrMaps)
library(sf)
library(scales)   # for percent()
library(ggplot2)
```

## Covid-19

```{r Covid_19, echo = FALSE}
# import the data
COVID_19_raw <- "https://www.worldometers.info/coronavirus/country/us/" %>%
  read_html() %>%
  html_table(fill=TRUE) %>%
  .[[1]]
# head(COVID_19_raw)

# colnames(COVID_19)

# select the rows and columns needed
COVID_19 <- data.frame(COVID_19_raw)
COVID_19 <- COVID_19[-c(1,53:nrow(COVID_19)),]
COVID_19 <- COVID_19 %>%
  dplyr::select(USAState, TotalCases, TotalDeaths,Tot.Cases.1M.pop,Deaths.1M.pop,Tests.1M.pop) %>%
  arrange(USAState)

# rename the columns
names(COVID_19) <-  c("state","TotalCases","TotalDeaths","Cases.1M.pop","Deaths.1M.pop","Tests.1M.pop")

# change state name to lower letter
COVID_19$state <- tolower(COVID_19$state)

# remove comma and numerical
COVID_19$TotalCases <- as.numeric(gsub(",", "", COVID_19$TotalCases))
COVID_19$TotalDeaths <- as.numeric(gsub(",", "", COVID_19$TotalDeaths))
COVID_19$Cases.1M.pop <- as.numeric(gsub(",", "", COVID_19$Cases.1M.pop))
COVID_19$Deaths.1M.pop <- as.numeric(gsub(",", "", COVID_19$Deaths.1M.pop))
COVID_19$Tests.1M.pop <- as.numeric(gsub(",", "", COVID_19$Tests.1M.pop))

# fill NA with 0
COVID_19$TotalDeaths <- replace_na(COVID_19$TotalDeaths, 0)

# head(COVID_19)
```

## Political Standing

```{r Political Standing, echo = FALSE}
# import the data
political_raw <- "https://www.nytimes.com/elections/2016/results/president" %>%
  read_html() %>%
  html_table(fill=TRUE) %>%
  .[[2]]
head(political_raw)

# select the needed columns
# add the region names by hand, pay attendsion on such as district of colunmbia which in short is D.C. and stand after delaware, stand in front of it.
political <- political_raw %>%
  dplyr::select(State,Clinton,Trump,Other) %>%
  arrange(State) %>%
  unique() %>% 
  mutate(state = c("alabama","alaska","arizona","arkansas","california","colorado","connecticut","district of columbia","delaware","florida","georgia","hawaii","idaho","illinois","indiana","iowa","kansas","kentucky","louisiana","massachusetts","maryland","maine","michigan","minnesota","mississippi","missouri","montana","north carolina","north dakota","new hampshire","new jersey","new mexico","new york","nebraska","nevada","ohio","oklahoma","oregon","pennsylvania","rhode island","south carolina","south dakota","tennessee","texas","utah","virginia","vermont","west virginia","washington","wisconsin","wyoming")) %>%
  dplyr::select(state,Clinton,Trump,Other)

# extracting the digit numbers and then divided by 100
political$Clinton <- as.numeric(gsub("[^0-9]","",political$Clinton))/100
political$Trump <- as.numeric(gsub("[^0-9]","",political$Trump))/100
political$Other <- as.numeric(gsub("[^0-9]","",political$Other))/100

# change the columns' names
colnames(political) <- c("state","Clinton","Trump","Other_poli")

# tried the following, but it's not numueric anymore
# percent(as.numeric(gsub("[^0-9]","",Clinton))/100)

# sum = Clinton+Trump+Other_poli is not 1 actually, checked true

head(political)
```

## Education

```{r Education, echo = FALSE}
# import the data
education_raw <- "https://worldpopulationreview.com/states/most-educated-states/" %>%
  read_html() %>%
  html_table(fill=TRUE) %>%
  .[[1]]
# head(education_raw)   # already clean enough

# select the needed col
education <- education_raw %>%
  dplyr::select(State,`Education Score`) %>%
  arrange(State)

# change the clo names
names(education) <- c("state","Education")

# lower the state col
education$state <- tolower(education$state)

# head(education)
```

## Population Density

```{r Population Density, echo = FALSE}
# import the data
pop_density_raw <- "https://simple.wikipedia.org/wiki/List_of_U.S._states_by_population_density" %>%
  read_html() %>%
  html_table(fill=TRUE) %>%
  .[[4]]
# head(pop_density_raw)

pop_density <- pop_density_raw %>%
  dplyr::select(`State/Territory/Division/Region`,`2013 estimatedpopulation`,`Land area(sqmi)`,`Population/sqmi`) %>%
  arrange(`State/Territory/Division/Region`)

# change column name 
names(pop_density) <- c("state","Population","Land","Density") 

# delete the comma and numerical the colums
pop_density$Population <- as.numeric(gsub(",", "", pop_density$Population))
pop_density$Land <- as.numeric(gsub(",", "", pop_density$Land))
pop_density$Density <- as.numeric(gsub(",", "", pop_density$Density))

# change state name to lower letter
pop_density$state <- tolower(pop_density$state)

# check density
pop_density_check <- pop_density %>%
  mutate(den = pop_density$Population/pop_density$Land)

# head(pop_density)
```

## GDP

```{r GDP, echo = FALSE, warning=FALSE}
# import the data
GDP_raw <- "https://en.wikipedia.org/wiki/List_of_U.S._states_and_territories_by_GDP" %>%
  read_html() %>%
  html_table(fill=TRUE) %>%
  .[[3]]
# head(GDP_raw)

# change cols name 
names(GDP_raw) <- c("rank","state","Q4_2019","GDP_portion","GDP_perCapita","Area")

# select the needed cols
GDP <- GDP_raw %>%
  dplyr::select(state,Q4_2019,GDP_portion,GDP_perCapita,Area) %>%
  arrange(state)

# delete the comma and numerical the colums
GDP$Q4_2019 <- as.numeric(gsub(",", "", GDP$Q4_2019))
GDP$GDP_portion <- as.numeric(GDP$GDP_portion)
GDP$GDP_perCapita <- as.numeric(gsub(",", "", GDP$GDP_perCapita))

# change state name to lower letter
GDP$state <- tolower(GDP$state)

# head(GDP)
```

## Full Table

```{r, echo = FALSE}
# join tables COVID_19 and political
full1 <- left_join(COVID_19,political,by="state")
# join table education and filled NA (district of columbia) with 0
full2 <- left_join(full1,education,by="state")
full2$Education <- replace_na(full2$Education, 0)
# join table pop_density
full3 <- left_join(full2,pop_density,by="state")
# join table pop_density
full <- left_join(full3,GDP,by="state")
head(full)

# export the .csv file
write_csv(full, "COVID19-Pol-Edu-Pop-GDP.csv")
```

## COVID-19, Political Standing, and GDP

```{r COVID-19, Political Standing, and GDP, echo = FALSE}
# select the needed columns
# combine two Political Standing colums and define
full_ForMap1 <- full %>%
  dplyr::select(state,Cases.1M.pop,Deaths.1M.pop,Clinton,Trump,GDP_perCapita) %>%
  mutate(Poli_standing = case_when(
    Clinton > Trump ~ "Clinton",
    Clinton < Trump ~ "Trump"))

# four states are very close
# Trump got Michigan, Pennsylvania, Wisconsin; Clinton got New Hampshire
full_ForMap1$Poli_standing <- replace_na(full_ForMap1$Poli_standing,"Trump")
full_ForMap1$Poli_standing[30] <- "Clinton"

# log transformation
full_ForMap1$Deaths.1M.pop <- log(full_ForMap1$Deaths.1M.pop)
full_ForMap1$Cases.1M.pop <- log(full_ForMap1$Cases.1M.pop)
full_ForMap1$GDP_perCapita <- log(full_ForMap1$GDP_perCapita)

Clinton_Map <- full_ForMap1 %>%
  dplyr::select(state,Cases.1M.pop,Deaths.1M.pop,Poli_standing,GDP_perCapita) %>%
  filter(Poli_standing=="Clinton")

Trump_Map <- full_ForMap1 %>%
  dplyr::select(state,Cases.1M.pop,Deaths.1M.pop,Poli_standing,GDP_perCapita) %>%
  filter(Poli_standing=="Trump")

reg1 <- lm(Deaths.1M.pop ~ GDP_perCapita, data = Clinton_Map)
# summary(reg1)
reg2 <- lm(Deaths.1M.pop ~ GDP_perCapita, data = Trump_Map)
# summary(reg2)
reg3 <- lm(Cases.1M.pop ~ GDP_perCapita, data = Clinton_Map)
# summary(reg3)
reg4 <- lm(Cases.1M.pop ~ GDP_perCapita, data = Trump_Map)
# summary(reg4)

ggplot() +
  #geom_abline(intercept = 8.388, slope = -0.829) + 
  geom_point(data=Clinton_Map, aes(x=GDP_perCapita, y=Deaths.1M.pop), color = "blue", size=2) +
  geom_point(data=Trump_Map, aes(x=GDP_perCapita, y=Deaths.1M.pop), color = "red", size=2) +
  geom_abline(intercept = -16.068, slope = 1.874, color = "blue") +
  geom_abline(intercept = 13.003, slope = -0.829, color = "red") +
  ggtitle("COVID-19 Death, Political Standing Map, and GDP") 

ggplot()+
  geom_point(data=Clinton_Map, aes(x=GDP_perCapita, y=Cases.1M.pop), color = "blue", size=2) +
  geom_point(data=Trump_Map, aes(x=GDP_perCapita, y=Cases.1M.pop), color = "red", size=2) +
  stat_function(fun = function(GDP_perCapita) -10.1383 + 1.6179*GDP_perCapita, data=Clinton_Map, color = "blue") +
  stat_function(fun = function(GDP_perCapita) 1.886 + 0.502*GDP_perCapita, data=Trump_Map, color = "red") +
  ggtitle("COVID-19 Case, Political Standing Map, and GDP")
```

## Education & Political Standing

```{r Education & Political Standing Map, echo = FALSE}
# education for map
education_ForMap <- full %>%
  dplyr::select(state, Education)
# match with choroplethr package
# change columns' names
names(education_ForMap) <- c("region", "value")

# political standing in Clinton for map
political_Clinton_ForMap <- full %>%
  dplyr::select(state, Clinton)
## match with choroplethr package
# change column name 
names(political_Clinton_ForMap) <- c("region", "value")

# political standing in Trump for map
political_Trump_ForMap <- full %>%
  dplyr::select(state, Trump)
## match with choroplethr package
# change column name 
names(political_Trump_ForMap) <- c("region", "value")

# create three side-by-side choropleth maps of Education & Political Standing in the USA
data(continental_us_states)
grid.arrange(state_choropleth(education_ForMap, title  = "Education Level in the US", zoom = continental_us_states))
grid.arrange(state_choropleth(political_Clinton_ForMap, title  = "Vote for Clinton in 2016 in the US", zoom = continental_us_states))
grid.arrange(state_choropleth(political_Trump_ForMap, title  = "Vote for Trump in 2016 in the US", zoom = continental_us_states))
```

## density, GDP, deaths

```{r COVID Death, Political Standing Map, and GDP, echo = FALSE}

```

```{r}
# select the needed columns
# combine two Political Standing colums and define
full_ForMap123 <- full %>%
  select(state,Deaths.1M.pop,Clinton,Trump,GDP_perCapita) %>%
  mutate(Poli_standing = case_when(
    Clinton > Trump ~ "Clinton",
    Clinton < Trump ~ "Trump"))

# four states are very close
# Trump got Michigan, Pennsylvania, Wisconsin; Clinton got New Hampshire
full_ForMap123$Poli_standing <- replace_na(full_ForMap123$Poli_standing,"Trump")
full_ForMap123$Poli_standing[30] <- "Clinton"

# log transformation
full_ForMap123$Deaths.1M.pop <- log(full_ForMap123$Deaths.1M.pop)
full_ForMap123$GDP_perCapita <- log(full_ForMap123$GDP_perCapita)

full_ForMap1234 <- data.frame(rep(full_ForMap123$state, times=2))
full_ForMap1234$Deaths.1M.pop[1:51] <-full_ForMap123$Deaths.1M.pop
full_ForMap1234$Deaths.1M.pop[52:102] <-full_ForMap123$Deaths.1M.pop
full_ForMap1234$GDP_perCapita[1:51] <-full_ForMap123$GDP_perCapita
full_ForMap1234$GDP_perCapita[52:102] <-full_ForMap123$GDP_perCapita
full_ForMap1234$Poli_type[1:51] <-full_ForMap123$Poli_standing
full_ForMap1234$Poli_type[52:102] <-full_ForMap123$Poli_standing
full_ForMap1234$Poli_vote[1:51] <-full_ForMap123$Clinton
full_ForMap1234$Poli_vote[52:102] <-full_ForMap123$Trump
```